# Generated by Django 5.0.6 on 2024-07-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('fabric_type', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('sole_material', models.CharField(max_length=255)),
                ('outer_material', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=255)),
            ],
            bases=('product.product',),
        ),
    ]
