# Generated by Django 5.0.6 on 2024-07-22 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nintendo',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Nintendo',
        ),
    ]
